artifact_uri: file:///C:/Users/LENOVO/OneDrive/Bureau/Projects/Chrun prediction/mlruns/900327966784936779/55a71d09c2dc43fc93a0ca1eba3a9a76/artifacts
end_time: 1764970328894
entry_point_name: ''
experiment_id: '900327966784936779'
lifecycle_stage: active
run_id: 55a71d09c2dc43fc93a0ca1eba3a9a76
run_name: bittersweet-colt-678
source_name: ''
source_type: 4
source_version: ''
start_time: 1764970316684
status: 3
tags: []
user_id: LENOVO
